# fly.toml app configuration file generated for prolong-request on 2023-04-20T04:18:27+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prolong-request"
primary_region = "ams"

[build]

[http_service]
force_https = true
internal_port = 80
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1
processes = ["app"]
